### ISSUE TITLE
请问下,这个源码和阿里云上提供的集成内核的toa是一样的吗?

### ISSUE THREAD

**Issue by sparkssssssss** [aliyun/alibabacloud-cdn-tool-toa#2]
阿里云帮助页面提供的https://www.alibabacloud.com/help/zh/doc-detail/52477.htm
但是要安装内核重启,
我用本仓库的编译加载后,无法看到真实ip.

**Comment by guangmuzhu** [comment]
> 请问下,这个源码和阿里云上提供的集成内核的toa是一样的吗?

是不一样的。建议参照官网文档，或联系售后支持。
